version: "3"
services:
  pth-api:
    restart: always
    ports:
      - "5001:80"
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORT=5001
    build: 
      context: .
      dockerfile: PTH.API/Dockerfile
    networks:
      clusternetwork:
        ipv4_address: 172.16.0.13

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      clusternetwork:
        ipv4_address: 172.16.0.14
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    stdin_open: true
    ports:
      - "8081:8081"
    links:
      - mongo
    networks:
      clusternetwork:
        ipv4_address: 172.16.0.15

networks:
  clusternetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
