version: "3"
services:
  poe-trade-helper-api:
    restart: always
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=5001
    build: 
      context: .
      dockerfile: PTH.API/Dockerfile

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    stdin_open: true
    ports:
      - "8081:8081"
    links:
      - mongo
      - "15672:15672"
